### ISSUE TITLE
Bump Version of Jest to Jest v28

### ISSUE THREAD

**Issue by mtpultz** [hirezio/single#10]
**Is your feature request related to a problem? Please describe.**
Dependency on Jest <  28.x.

**Describe the solution you'd like**
Update the dependencies to allow for Jest v28.x.

**Describe alternatives you've considered**
Downgrading Jest to v27, but package appears to work under v28.

**Comment by shairez** [comment]
Thanks @mtpultz 

Want to open a PR for that? :)
