### ISSUE TITLE
Bump Jest to v29

### ISSUE THREAD

**Issue by awarrington0895** [hirezio/single#11]
**Is your feature request related to a problem? Please describe.**
Upgrading Nx/Angular project to v15 upgrades Jest to v29 and causes peer dependency conflicts with this library in newer versions of npm.

**Describe the solution you'd like**
Update the dependencies to allow for Jest v29.x.

**Describe alternatives you've considered**
Downgrade our project, but would rather stay up to date with recommendations from Nx.

**Additional context**
Happy to take a stab at contributing the upgrade if you're busy.  _Seems_ fairly straightforward.

**Comment by shairez** [comment]
Thanks @awarrington0895 
Would apprecaite a PR (there are similar ones in the past if you want to take a look and copy the same approach)

Thanks!

**Comment by awarrington0895** [comment]
Thanks for the quick response @shairez .  I'll review the contribution guide and the previous Jest PR and take a whack at it first thing tomorrow.
